# SwiftLint config (package root)

strict: true

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Package.resolved

check_for_updates: false

disabled_rules:
  - todo

opt_in_rules:
  - force_unwrapping
  - empty_count
  - empty_string
  - first_where
  - contains_over_first_not_nil
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20
  
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  allowed_symbols: ["_"]
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - URL

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

force_try:
  severity: error
force_cast:
  severity: error
